### ISSUE TITLE
Creation of cluster fails to start control-plane with: context deadline exceeded

### ISSUE THREAD

**Issue by pbabinca** [konflux-ci/konflux-ci#205] opened 2024-07-10 17:51 UTC
I'm unable to to bootstrap cluster. It isn't obvious to me what causes the failure, so here is almost full output:

```bash
$ kind create cluster --name konflux --config kind-config.yaml
enabling experimental podman provider
Creating cluster "konflux" ...
 ✓ Ensuring node image (kindest/node:v1.30.0) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✗ Starting control-plane 🕹️ 
Deleted nodes: ["konflux-control-plane"]
ERROR: failed to create cluster: failed to init node with kubeadm: command "podman exec --privileged konflux-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
Command Output: I0710 17:20:03.702786     132 initconfiguration.go:260] loading configuration from "/kind/kubeadm.conf"
W0710 17:20:03.705887     132 initconfiguration.go:348] [config] WARNING: Ignored YAML document with GroupVersionKind kubeadm.k8s.io/v1beta3, Kind=JoinConfiguration
[init] Using Kubernetes version: v1.30.0
[certs] Using certificateDir folder "/etc/kubernetes/pki"
I0710 17:20:03.721044     132 certs.go:112] creating a new certificate authority for ca
[certs] Generating "ca" certificate and key
I0710 17:20:03.835223     132 certs.go:483] validating certificate period for ca certificate
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [konflux-control-plane kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local localhost] and IPs [10.96.0.1 10.89.0.2 127.0.0.1]
[certs] Generating "apiserver-kubelet-client" certificate and key
I0710 17:20:04.152857     132 certs.go:112] creating a new certificate authority for front-proxy-ca
[certs] Generating "front-proxy-ca" certificate and key
I0710 17:20:04.278687     132 certs.go:483] validating certificate period for front-proxy-ca certificate
[certs] Generating "front-proxy-client" certificate and key
I0710 17:20:04.466347     132 certs.go:112] creating a new certificate authority for etcd-ca
[certs] Generating "etcd/ca" certificate and key
I0710 17:20:04.593205     132 certs.go:483] validating certificate period for etcd/ca certificate
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [konflux-control-plane localhost] and IPs [10.89.0.2 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [konflux-control-plane localhost] and IPs [10.89.0.2 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
I0710 17:20:05.536090     132 certs.go:78] creating new public/private key files for signing service account users
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
I0710 17:20:05.611977     132 kubeconfig.go:112] creating kubeconfig file for admin.conf
[kubeconfig] Writing "admin.conf" kubeconfig file
I0710 17:20:05.688477     132 kubeconfig.go:112] creating kubeconfig file for super-admin.conf
[kubeconfig] Writing "super-admin.conf" kubeconfig file
I0710 17:20:05.891181     132 kubeconfig.go:112] creating kubeconfig file for kubelet.conf
[kubeconfig] Writing "kubelet.conf" kubeconfig file
I0710 17:20:06.083404     132 kubeconfig.go:112] creating kubeconfig file for controller-manager.conf
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
I0710 17:20:06.139208     132 kubeconfig.go:112] creating kubeconfig file for scheduler.conf
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
I0710 17:20:06.460519     132 local.go:65] [etcd] wrote Static Pod manifest for a local etcd member to "/etc/kubernetes/manifests/etcd.yaml"
I0710 17:20:06.460560     132 manifests.go:103] [control-plane] getting StaticPodSpecs
I0710 17:20:06.460808     132 certs.go:483] validating certificate period for CA certificate
I0710 17:20:06.460894     132 manifests.go:129] [control-plane] adding volume "ca-certs" for component "kube-apiserver"
I0710 17:20:06.460901     132 manifests.go:129] [control-plane] adding volume "etc-ca-certificates" for component "kube-apiserver"
I0710 17:20:06.460906     132 manifests.go:129] [control-plane] adding volume "k8s-certs" for component "kube-apiserver"
I0710 17:20:06.460911     132 manifests.go:129] [control-plane] adding volume "usr-local-share-ca-certificates" for component "kube-apiserver"
I0710 17:20:06.460916     132 manifests.go:129] [control-plane] adding volume "usr-share-ca-certificates" for component "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
I0710 17:20:06.462025     132 manifests.go:158] [control-plane] wrote static Pod manifest for component "kube-apiserver" to "/etc/kubernetes/manifests/kube-apiserver.yaml"
I0710 17:20:06.462047     132 manifests.go:103] [control-plane] getting StaticPodSpecs
I0710 17:20:06.462262     132 manifests.go:129] [control-plane] adding volume "ca-certs" for component "kube-controller-manager"
I0710 17:20:06.462275     132 manifests.go:129] [control-plane] adding volume "etc-ca-certificates" for component "kube-controller-manager"
I0710 17:20:06.462305     132 manifests.go:129] [control-plane] adding volume "flexvolume-dir" for component "kube-controller-manager"
I0710 17:20:06.462311     132 manifests.go:129] [control-plane] adding volume "k8s-certs" for component "kube-controller-manager"
I0710 17:20:06.462315     132 manifests.go:129] [control-plane] adding volume "kubeconfig" for component "kube-controller-manager"
I0710 17:20:06.462319     132 manifests.go:129] [control-plane] adding volume "usr-local-share-ca-certificates" for component "kube-controller-manager"
I0710 17:20:06.462324     132 manifests.go:129] [control-plane] adding volume "usr-share-ca-certificates" for component "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
I0710 17:20:06.463324     132 manifests.go:158] [control-plane] wrote static Pod manifest for component "kube-controller-manager" to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
I0710 17:20:06.463344     132 manifests.go:103] [control-plane] getting StaticPodSpecs
I0710 17:20:06.463562     132 manifests.go:129] [control-plane] adding volume "kubeconfig" for component "kube-scheduler"
I0710 17:20:06.464166     132 manifests.go:158] [control-plane] wrote static Pod manifest for component "kube-scheduler" to "/etc/kubernetes/manifests/kube-scheduler.yaml"
I0710 17:20:06.464185     132 kubelet.go:68] Stopping the kubelet
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
I0710 17:20:06.795612     132 loader.go:395] Config loaded from file:  /etc/kubernetes/admin.conf
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests"
[kubelet-check] Waiting for a healthy kubelet. This can take up to 4m0s
[kubelet-check] The kubelet is healthy after 1.002349472s
[api-check] Waiting for a healthy API server. This can take up to 4m0s
I0710 17:20:07.800747     132 round_trippers.go:553] GET https://konflux-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
I0710 17:20:08.300651     132 round_trippers.go:553] GET https://konflux-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
```
8< snipped here to remove ~ 466 repeated lines like previous ones. Now continuing:

```bash
I0710 17:24:06.801021     132 round_trippers.go:553] GET https://konflux-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
I0710 17:24:07.300615     132 round_trippers.go:553] GET https://konflux-control-plane:6443/healthz?timeout=10s  in 1 milliseconds
[api-check] The API server is not healthy after 4m0.000226692s

Unfortunately, an error has occurred:
	context deadline exceeded

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI.
Here is one example how you may list all running Kubernetes containers by using crictl:
	- 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
	Once you have found the failing container, you can inspect its logs with:
	- 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock logs CONTAINERID'
couldn't initialize a Kubernetes cluster
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runWaitControlPlanePhase.func1
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:110
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runWaitControlPlanePhase
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:125
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:259
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:446
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:232
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:128
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.7.0/command.go:992
k8s.io/kubernetes/cmd/kubeadm/app.Run
	k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:52
main.main
	k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	runtime/proc.go:271
runtime.goexit
	runtime/asm_amd64.s:1695
error execution phase wait-control-plane
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:260
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:446
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:232
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:128
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.7.0/command.go:992
k8s.io/kubernetes/cmd/kubeadm/app.Run
	k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:52
main.main
	k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	runtime/proc.go:271
runtime.goexit
	runtime/asm_amd64.s:1695
```

---

I'm running this in a VM with following configuration (ran just before bootstrapping the cluster):
```bash
$ sudo inxi --system --machine --memory-short --disk --cpu --za
System:
  Kernel: 6.8.5-301.fc40.x86_64 arch: x86_64 bits: 64
  Console: pty pts/1 Distro: Fedora Linux 40 (Server Edition)
Machine:
  Type: Kvm System: QEMU product: Standard PC (Q35 + ICH9, 2009) v: pc-q35-8.1 serial: N/A
  Mobo: N/A model: N/A serial: N/A BIOS: SeaBIOS v: 1.16.3-1.fc39 date: 04/01/2014
Memory:
  System RAM: total: 12 GiB available: 11.68 GiB used: 640.3 MiB (5.4%)
  Report: arrays: 1 capacity: 12 GiB installed: 12 GiB slots: 1 active: 1 type: RAM
    eec: Multi-bit ECC
CPU:
  Info: 4x 1-core model: N/A bits: 64 type: SMP cache: L2: 4x 512 KiB (2 MiB)
  Speed (MHz): avg: 2400 min/max: N/A cores: 1: 2400 2: 2400 3: 2400 4: 2400
Drives:
  Local Storage: total: 20 GiB used: 2.29 GiB (11.4%)
  ID-1: /dev/vda model: N/A size: 20 GiB
```

All the VM storage is on pool with SATA 3.1, 5400 rpm HDD.

And going even more back in the past, just after fresh Fedora Server 40 installation I ran:

```bash
$ sudo dnf install -qy podman git-core inxi
$ curl --silent --show-error -Lo ./kind https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64
$ sudo install -o root -g root -m 0755 kind /usr/local/bin/kind
$ curl --silent --show-error -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
$ sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
$ sudo sysctl fs.inotify.max_user_watches=524288
$ sudo sysctl fs.inotify.max_user_instances=512
$ git clone https://github.com/konflux-ci/konflux-ci.git
$ cd konflux-ci
$ sed -i s/memory=8Gi/memory=12Gi/ kind-config.yaml
```

And finally HEAD of the `konflux-ci` repo is at:

```bash
$ git log --pretty=format:"%h%x09%x09%ad%x09%s" -1
c165bae         Wed Jul 10 14:28:22 2024 +0300  Merge pull request #198 from yftacherzog/test-pvc-default-sa
```

Since I managed to install this last week, I tried to:

```bash
$ git reset --hard 255d3a0e5118195029777942bc91444bf788d8ed
HEAD is now at 255d3a0 konftool:gh_app: GH App creation flow (partial)
$ git log --pretty=format:"%h%x09%x09%ad%x09%s" -1
255d3a0         Wed Jun 26 09:06:13 2024 +0300  konftool:gh_app: GH App creation flow (partial)
```

and with that one:

```bash
$ kind create cluster --name konflux --config kind-config.yaml
enabling experimental podman provider
Creating cluster "konflux" ...
 ✓ Ensuring node image (kindest/node:v1.30.0) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-konflux"
You can now use your cluster with:

kubectl cluster-info --context kind-konflux

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
```

I haven't bisected particular problematic commit here.

**Comment by yftacherzog** [comment] 2024-07-11 04:51
Thanks @pbabinca for raising those issues!

I think the fact that it fails during cluster creation means the issue is with either the OS configs or available resources.
The only thing in the repo that affects cluster creation is the `kind-config.yaml` file, which haven't changed for some time.

The two things I can think of is:
1. podman installation: Following [Kind rootless configs](https://kind.sigs.k8s.io/docs/user/rootless/) seem to help with those. Having said that, I would not expect to see it failing in different places every time if that was the reason.
2. Not enough resources: something looks off there. We didn't see the cluster requiring more than 8 gigs of RAM for the setup, and it seems to me as processes are having hard time starting, which makes me think again on not enough CPU cores.

What I can suggest is trying to run it on a bigger VM. You should be able to set one up in cnv-engineering. I took some notes when doing that: https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1715150561436869?thread_ts=1715092931.327899&cid=C02CTEB3MMF

**Comment by gbenhaim** [comment] 2024-07-22 12:09
@pbabinca have you tried the suggestion above? can we close this issue?

**Closed** 2024-09-17 09:22 UTC
